# .gitlab-ci.yml
#
# YAML script to implement CI/CD for the adaptgui project
#

image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
#   # Note: That there is no real "build" phase for a Python project..
    - build
    - test

build_job:
    stage: build
    script:
#
#   # Basic Ubuntu
        - apt-get update --yes
    # Update pip
        - python -m pip install -U pip

#   Python packages
        - python -m pip install -U matplotlib
        - pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

#   Tools for testing
        - pip install coverage
        - pip install pylint

verify_code:
    stage: test
    script:
    - cd tests
    - python test_pylint.py demo_3d_plot.py 9.50

validate_pdf_calcs:
    stage: test
    script:
    - cd tests
    - python test_distrib.py

coverage_test:
    stage: test
    script:
    - cd tests
    - coverage erase
    - coverage run --source=../ test_coverage.py
    - coverage report --omit=*/tests/*,*/venv/*,*init__* --fail-under=80 
