#! /usr/bin/env python
"""
# File: test_coverage.py
#
# Author: Mike Lum
# Copyright 2021 by the author.
#
# Usage: python -m test_coverage
#
# Description: Compares the bivariate normal pdf generated by numpy with one generated using
# PyTorch.
# Most of the code herein is borrowed from:
#   https://towardsdatascience.com/a-python-tutorial-on-generating-and-plotting-a-3d-guassian-distribution-8c6ec6c41d03
#
# Revision History:
#    Date        Vers.    Author    Description
#   2021-08-09   1.0a1    Lum       New file
#   2021-08-12   1.0f1    Lum       Docstrings
"""

# Python library imports
import os
import sys

# External libraries
from matplotlib import pyplot

# Internal functions to test
sys.path.append('..')   # Necessary for running in tests directory
import demo_3d_plot as d3d

# Constants to test
DOMAIN = 6.
MEAN = 4.
VARIANCE = 0.25

if __name__ == '__main__':
    # There are three functions to test in demo_3d_plot. One of which has two 
    # code branches. We test all four options here.
    test_xs, test_ys, test_zs = d3d.bivariate_normal_pdf(DOMAIN, MEAN, VARIANCE)

    d3d.make_plot(test_xs, test_ys, test_zs, interactive=False)

    d3d.function_to_test(True)
    d3d.function_to_test(False)

